# Generated by Django 5.1 on 2024-09-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanevent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='ScanEvent',
        ),
    ]
