# Generated by Django 5.1 on 2024-09-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanevent', '0002_rename_courses_scanevent'),
    ]

    