# Generated by Django 5.1 on 2024-09-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalled_drug', '0002_rename_pharmacy_id_recalleddrug_scan_id_and_more'),
        ('scanevent', '0003_remove_scanevent_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recalleddrug',
            name='reason_for_recall',
        ),
        migrations.AddField(
            model_name='recalleddrug',
            name='reason',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recalleddrug',
            name='scan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanevent.scanevent'),
        ),
    ]
