# Generated by Django 5.1 on 2024-09-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.PositiveSmallIntegerField()),
                ('town', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=30)),
                ('pharmacy_id', models.PositiveSmallIntegerField()),
                ('pharmacy_name', models.CharField(max_length=50)),
            ],
        ),
    ]
