# Generated by Django 5.1 on 2024-09-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_rename_county_pharmacy_street_remove_pharmacy_town'),
        ('recalled_drug', '0003_remove_recalleddrug_reason_for_recall_and_more'),
        ('user_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='pharmacy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='recalled_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recalled_drug.recalleddrug'),
        ),
    ]
