# Generated by Django 5.1 on 2024-09-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_pharmacy_pharmacy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='county',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='town',
        ),
    ]
